codenotary/immudb.io

- src/docs/immugw/immugw-curl.md
add new examples to use curl  to work with of immugw
> fix curl commands

- src/_blog/2020-06-05-step-by-step-guide.md
- src/immudb/README.md
- src/quickstart.md
Just some small typos: `IMMUGW_IMMUDB-ADDRESS` instead of `IMMUGW_IMMUDB_ADDRESS`.
Note that I didn't do anything about building the HTMLs. If you have a feedback about it, I'd gladly do it. 😊
> typos on IMMUGW_IMMUDB_ADDRESS

- src/0.9.0/how-it-works.md
Does "immudb short research paper" exist in any form?
Not sure how you want me to proceed with these sections:
> First pass edits to how-it-works.md

- README.md
- src/.vuepress/styles/palette.styl
A small change with a big impact, especially on code snippets readability.
Thanks @Hextar for the hint.
> contentWidth 90% for better code readability

- src/.vuepress/theme/util/index.js
- src/0.9.2/README.md
- src/0.9.2/apis-references.md
- src/0.9.2/careers/README.md
- src/0.9.2/careers/job-descriptions/qa-automation-engineer.md
- src/0.9.2/careers/job-descriptions/senior-software-engineer-go.md
- src/0.9.2/careers/job-descriptions/software-development-team-lead.md
- src/0.9.2/command-reference.md
- src/0.9.2/how-it-works.md
- src/0.9.2/immuadmin/README.md
- src/0.9.2/immuclient/README.md
- src/0.9.2/immudb/README.md
- src/0.9.2/immudb/grpc-interface.md
- src/0.9.2/immugw/curl.md
- src/0.9.2/immugw/index.md
- src/0.9.2/jumpstart.md
- src/0.9.2/quickstart.md
- src/0.9.2/sdks-api.md
Adds 0.9.2 to the list of releases
> feat: Add 0.9.2

- src/.vuepress/config.js
- src/.vuepress/theme/components/DiscordChatWidget.vue
- src/.vuepress/theme/global-components/CnButton.vue
- src/.vuepress/theme/global-components/CnSocialButton.vue
- src/.vuepress/theme/layouts/Layout.vue
- src/0.8.0/how-it-works.md
- src/0.8.1/how-it-works.md
> Add Discord widget

- src/master/operations/specs.md
> fix references link

- package-lock.json
- src/1.0.0/reference/sql.md
- src/master/reference/sql.md
- updating sql reference to match the webconsole demo data
This PR is a draft due to some SQL queries currently not working. As soon as those will be fixed the PR could be unlocked.
> Feat sql reference rewrite

- src/master/reference/sql.md
> fix: Add sub-queries into the SQL reference

- src/master/reference/sql.md
> feat(sql): Add timestamp documentation.

- src/.vuepress/enhanceApp.js
- src/master/develop/deleting.md
- src/master/develop/updating-deleting.md
- src/master/reference/sql.md
Update and delete section for key-value store
> update and delete section

- src/1.1.0/develop/auditor.md
- src/1.2.1/develop/auditor.md
- src/master/develop/auditor.md
> fix(develop/auditor): Fix typos

- package-lock.json
- package.json
- added resolution rules to package.json
> fix: solved vulnerabilities

- src/0.8.0/how-it-works.md
- src/0.8.1/how-it-works.md
- src/0.9.0/immudb/README.md
- src/0.9.1/immudb/README.md
- src/0.9.2/immudb/README.md
- src/1.0.0/old/immudb.md
- src/1.1.0/old/immudb.md
- src/1.2.1/old/immudb.md
- src/1.2.2/old/immudb.md
- src/master/old/immudb.md
> fix: Fix the name of signing key env var

- src/master/quickstart.md
Added examples to show how to create and update databases, look up transaction id's etc
Addresses documentation requirements from issue #997
I was unable to find how to look up the whole history. I would like to know that for my usage as well.
> Added immuadmin and database change examples

- src/.vuepress/enhanceApp.js
- src/master/operations/backwards-compatibility.md
> docs: Document immudb 1.1 proof compatibility mode

- src/master/jumpstart.md
- src/master/quickstart.md
> remove duplicated sections

- src/1.2.4/develop/embedding.md
- src/master/develop/embedding.md
> chore: update embedded samples to work with latest release

- src/1.2.4/develop/embedding.md
- src/master/develop/embedding.md
> chore: ensure kv tx is closed

- src/master/reference/sql.md
> feat: Document ALTER TABLE ADD/RENAME COLUMN

- src/master/reference/sql.md
> document union operator

- src/master/reference/sql.md
> upgrade sql temporal queries support

- src/master/reference/sql.md
> document tx conflicts

- src/master/reference/sql.md
> docs(sql): Document SQL catalog queries.

- .github/workflows/build.yml
- checks/configuration.sh
- src/master/running/configuration.md
> fix: Update and add validation for configuration options docs.

- src/1.4.0/connecting/sdks.md
- src/master/connecting/sdks.md
> chore: Update SDK version list

- src/master/management/user.md
> feat(management/user): Add documentation for changing user's password

- src/master/management/database.md
- src/master/production/replication.md
- src/master/production/sync-replication.md
- src/master/running/configuration.md
> fix: Update naming conventions related to replication

- src/master/connecting/sdks.md
- src/master/develop/deleting.md
- src/master/develop/indexes.md
- src/master/develop/queries-history.md
- src/master/develop/reading.md
- src/master/develop/sql/transactions.md
- src/master/develop/streams.md
- src/master/develop/transactions.md
> upgrade immudb4j documentation and code snippets

- src/1.2.1/develop/deleting.md
- src/1.2.1/develop/expiration.md
- src/1.2.2/develop/deleting.md
- src/1.2.2/develop/expiration.md
- src/1.2.3/develop/deleting.md
- src/1.2.3/develop/expiration.md
- src/1.2.4/develop/deleting.md
- src/1.2.4/develop/expiration.md
- src/1.3.0/develop/deleting.md
- src/1.3.0/develop/expiration.md
- src/1.3.1/develop/deleting.md
- src/1.3.1/develop/expiration.md
- src/1.3.2/develop/deleting.md
- src/1.3.2/develop/expiration.md
- src/1.4.0/develop/deleting.md
- src/1.4.0/develop/expiration.md
- src/1.4.1/develop/deleting.md
- src/1.4.1/develop/expiration.md
- src/master/develop/deleting.md
- src/master/develop/expiration.md
> typo fixed

- src/1.9DOM.0/samples/go.md
- src/1.9DOM.1/samples/go.md
- src/master/samples/go.md
> Fix broken links to golang sdk
